config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root 'home#index'

  get 'dashboard' => 'home#dashboard'

  resources :places
  resources :reviews

  scope 'api' do
    get     'get_places'                   => 'places#get_places'
    get     'get_users'                    => 'users#get_users'

    get     'user_reviews/:user_id'        => 'reviews#user_reviews'
    get     'places/'                      => 'places#get_places'

    post    'user_reviews/:user_id'        => 'reviews#create'
    get     'user_reviews/:user_id/:id'    => 'reviews#show'
    delete  'user_reviews/:user_id/:id'    => 'reviews#destroy'
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username

  has_many :reviews, dependent: :destroy

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render "home/index"
  end

  def dashboard
    @users = User.all
    @places = Place.all
    @reviews = Review.all

    render "home/dashboard"
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
    @place = Place.new
    render "places/index"
  end

  def create
    @place = Place.new(place_params)
    @place.save

    redirect_to places_path
  end

  def edit
    @place = Place.find(params[:id])
  end


  def show
    @place = Place.find(params[:id])
    @review = Review.new
    @reviews = Review.where(:place_id => @place.id)

  end

  def update
    @place = Place.find(params[:id])

    if @place.update(place_params)
      redirect_to @place
    else
      render 'edit'
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    redirect_to places_path
  end


  def get_places
    @places = Place.all
    render :json => @places.to_json(:include => {:reviews => { :include => :user }})
  end


  private
    def place_params
      params.require(:place).permit(:name, :description, :address)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
    @review = Review.new(review_params)

    @review.save


    respond_to do |format|
      format.html {  redirect_to place_path(@review.place_id) }
      format.json { head :no_content }
    end
  end

  def edit
    @review = Review.find(params[:id])
  end


  def show
    if params[:user_id]
      @review = Review.where(:id => params[:id]).where(:user_id => params[:user_id])
    end

    render :json => @review.to_json
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(place_params)
      redirect_to @review
    else
      render 'edit'
    end
  end

  def destroy
    @review = Review.find(params[:id])

    place = @review.place_id

    @review.destroy
    respond_to do |format|
      format.html {  redirect_to place_path(place) }
      format.json { head :no_content }
    end
  end

  def user_reviews
    @user_id = params[:user_id]
    @reviews = Review.where(:user_id => @user_id)
    render :json => @reviews.to_json(:include => :place)
  end


  private
  def review_params
    params.require(:review).permit(:food_eaten, :description, :place_id, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def get_users
    @users = User.all
    render :json => @users.to_json(:include => {:reviews => {:include => :place}})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/views/home/dashboard.haml
%h1 Dashboard
=link_to 'Home', root_path
%h3 At a glance
%p Number of Users: #{@users.size} | Number of Reviews: #{@reviews.size} | Number of Places: #{@places.size}

%h3 User stats
- @users.each do |user|
  %p #{user.username} has made #{user.reviews.count} reviews
%h2 Deep dive
- @places.each do |place|
  %h3 Place Name: #{place.name}
  %p Description: #{place.description}
  %h3 Reviews for #{place.name}:
  - if place.reviews.count == 0
    %p No reviews yet
  - place.reviews.each do |review|
    %h4 Reviewer: #{User.find(review.user_id).username}| Food Eaten: #{review.food_eaten}
    %p Thoughts on the vibe: #{review.description}
  %hr

app/views/home/index.haml
= content_for :css_placeholder do
  = stylesheet_link_tag "manifests/home"
= content_for :js_placeholder do
  = javascript_include_tag 'manifests/home'

- if current_user.present?
  :javascript
    var USER_ID = '#{current_user.id }'
- else
  :javascript
    var USER_ID = 'nil'

%h1 Cupcake-n-Cookie Crawl
%h3
  Review all 10 places in one day!
  =link_to 'View Dashboard', dashboard_path


- if current_user.present?
  #app
    %h3 Loading
- else
  %h1 Login to continue!


:plain
  <script id="index-template" type="text/x-mustache-template">
    <h2 class="text-center">You've written {{count}} reviews!</h2>
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#places" role="tab" data-toggle="tab">Places</a></li>
      <li><a href="#reviews" role="tab" data-toggle="tab">My Reviews</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="places">
        <h2 class="text-center">Cookie and Cupcake Places</h2>
        <div class="places"></div>
      </div>
      <div class="tab-pane" id="reviews">
        <h2>Your Reviews</h2>
        <div class="reviews"></div>
      </div>
    </div>

  </script>

  <script id="index-form-template" type="text/x-mustache-template">
    <div class="well">
      <legend>Add review</legend>
      <fieldset>
      <div class='control-group'>
        <label class='control-label' for='food_eaten'>Food Eaten</label>
        <div class='controls'>
          <input type='text' class='form-control input-xlarge' id='food_eaten'>
        </div>
      </div>
      <div class='control-group'>
        <label class='control-label' for='description'>How was the vibe?</label>
        <div class='controls'>
          <input type='text' class='form-control input-xlarge' id='description'>
        </div>
      </div>
      <hr>
      <div class="form-actions">
        <button type="submit" class="btn btn-block btn-primary">Add Review</button>
      </div>
      </fieldset>
    </div>
  </script>

  <script id="index-review-template" type="text/x-mustache-template">
    <h4><strong>Place:</strong> {{place_name}}</h4>
    <h4><strong>Food I Ate:</strong> {{food_eaten}}</h4>
    <h4><strong>Thoughts on the vibe:</strong> {{description}}</h4>
    <div class="delete btn btn-xs btn-danger"> Delete Review</div>
    <p>Reviewed at: {{review_time}}
    <hr>
  </script>

  <script id="index-place-template" type="text/x-mustache-template">
    <h2>{{name}} <small>{{description}}</small></h2>

    <p>Address: <a href="https://www.google.com/maps/place/{{address}}" target="_blank">{{address}}</a></p>
    <p>Number of Reviews: {{reviewCount}}</p>
    <p>Have you reviewed this place? {{currentUserReviewed}}</p>
  </script>

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{charset: "utf-8"}/
    %title Cupcake-n-Cookie Crawl
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    = stylesheet_link_tag "manifests/global"
    = csrf_meta_tags
    = yield :css_placeholder
  %body
    .container
      - flash.each do |type, message|
        %div{class: "alert #{bootstrap_class_for(type)} fade in"}
          %button.close{"data-dismiss" => "alert"} ×
          = message
      - if user_signed_in?
        Hello there,
        = succeed "." do
          %strong= current_user.username
        %br
        = link_to 'Edit profile', edit_user_registration_path
        |
        \#{link_to "Logout", destroy_user_session_path, method: :delete}
      - else
        = link_to "Sign up", new_user_registration_path
        |
        \#{link_to "Login", new_user_session_path}
      = yield
    = javascript_include_tag 'manifests/global'
    = yield :js_placeholder
    :javascript
      $(document).ajaxSend(function(e, xhr, options) {
      var token = $("meta[name='csrf-token']").attr("content");
        xhr.setRequestHeader("X-CSRF-Token", token);
      });

app/views/places/edit.haml
%h1 Editing #{@place.name}
= form_for :place, url: place_path(@place), method: :patch do |f|
  - if @place.errors.any?
    #error_explanation
      %h2
        = pluralize(@place.errors.count, "error")
        prohibited
        this article from being saved:
      %ul
        - @place.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :description
    %br/
    = f.text_area :description
  %p
    = f.submit
= link_to 'Back', places_path

app/views/places/index.haml
%h1 Places

%table
  %tr
    %th Place
    %th Description
  - @places.each do |place|
    %tr
      %td= place.name
      %td= place.description
      %td #{link_to "View this place", place_path(place)}
      %td #{link_to "Edit this place", edit_place_path(place)}
      %td #{link_to "Delete this place", place_path(place), :method => :delete}


%h2 Add a place
= form_for(@place) do |f|
  %label Name
  = f.text_field :name
  %label Address
  = f.text_field :address
  %label Description
  = f.text_field :description
  = f.submit "Add Place"

app/views/places/show.haml
%h1= @place.name

%p= @place.description

%h3 Reviews
%table.table-striped.table-hover
  %tr
    %th Food Eaten
    %th Overall thoughts
  - @reviews.each do |review|
    %tr
      %td= review.food_eaten
      %td= review.description
      %td #{link_to "Delete this Review", review_path(review), :method => :delete}

%hr
%h3 Add Review
= form_for(@review) do |f|
  %label Food Eaten
  = f.text_field :food_eaten
  %label Overall thoughts
  = f.text_field :description
  = f.hidden_field :user_id, :value => current_user.id
  = f.hidden_field :place_id, :value => @place.id
  = f.submit "Add Review"